<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11785" started-at="2022-04-20T10:37:17 IST" finished-at="2022-04-20T10:37:28 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11785" started-at="2022-04-20T10:37:17 IST" finished-at="2022-04-20T10:37:28 IST">
      <class name="testClasses.Kite_Login_Test">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testClasses.Kite_Login_Test@6dde5c8c]" name="launchBrowser" is-config="true" duration-ms="8128" started-at="2022-04-20T10:37:17 IST" finished-at="2022-04-20T10:37:25 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="refresh()[pri:0, instance:testClasses.Kite_Login_Test@6dde5c8c]" name="refresh" is-config="true" duration-ms="11" started-at="2022-04-20T10:37:25 IST" finished-at="2022-04-20T10:37:25 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- refresh -->
        <test-method status="FAIL" signature="validCredentialLogIn()[pri:0, instance:testClasses.Kite_Login_Test@6dde5c8c]" name="validCredentialLogIn" duration-ms="3011" started-at="2022-04-20T10:37:25 IST" finished-at="2022-04-20T10:37:28 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ALO737] but found [AL0737]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ALO737] but found [AL0737]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testClasses.Kite_Login_Test.validCredentialLogIn(Kite_Login_Test.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentialLogIn -->
        <test-method status="PASS" signature="takesScreenshot(org.testng.ITestResult)[pri:0, instance:testClasses.Kite_Login_Test@6dde5c8c]" name="takesScreenshot" is-config="true" duration-ms="405" started-at="2022-04-20T10:37:28 IST" finished-at="2022-04-20T10:37:28 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validCredentialLogIn status=FAILURE method=Kite_Login_Test.validCredentialLogIn()[pri:0, instance:testClasses.Kite_Login_Test@6dde5c8c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takesScreenshot -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testClasses.Kite_Login_Test@6dde5c8c]" name="closeBrowser" is-config="true" duration-ms="168" started-at="2022-04-20T10:37:28 IST" finished-at="2022-04-20T10:37:28 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- testClasses.Kite_Login_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
